name: Blank Issue
description: Create a blank issue. Always first use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.

body:
  - type: markdown
    attributes:
        value: |
          **Thanks 🩷 for taking the time to fill out this bug report! Before proceeding, please read the following:**

          This form is ONLY FOR DEVELOPERS. Your issue will be closed and you will be possibly blocked from the repo if you ignore this.

          Don't use this form, unless:
          - You're a Vencord contributor,
          - You we're given explicit permission to use this form by a moderator in our support server,
          - You are filing a security related report.

  - type: textarea
    id: content
    attributes:
        label: Content
    validations:
        required: true

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      options:
          - label: I have read the requirements for opening an issue above
            required: true
