name: 🐛 Bug / Crash Report
description: Create a bug or crash report for Vesktop. Always use our support channel! Only use this form if you're a contributor or we're told to do so in the support channel.
labels: [Bug]
title: "[Bug] <title>"

body:
  - type: markdown
    attributes:
        value: |
          **Thanks 🩷 for taking the time to fill out this bug report! Before proceeding, please read the following:**

          This form is ONLY FOR DEVELOPERS. Your issue will be closed and you will be possibly blocked from the repo if you ignore this.

          Please don't use this form, unless:
          - You're a Vencord contributor,
          - You we're given explicit permission to use this form by a moderator in our support server.

          Don't use this form for security related issues, [create security advisory instead.](https://github.com/Vendicated/Vencord/security/advisories/new)
  
  - type: input
    id: discord
    attributes:
        label: Discord Account
        description: Who on Discord is making this request? Not required but encouraged for easier follow-up.
        placeholder: username#0000
    validations:
        required: false

  - type: textarea
    id: bug-description
    attributes:
        label: What happens when the bug or crash occurs?
        description: Where does this bug or crash occur, when does it occur, etc.
        placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ...
    validations:
        required: true

  - type: textarea
    id: expected-behaviour
    attributes:
        label: What is the expected behaviour?
        description: Simply detail what the expected behaviour is.
        placeholder: I expect Vencord/Discord to open the ... page instead of ..., it prevents me from doing ...
    validations:
        required: true

  - type: textarea
    id: steps-to-take
    attributes:
        label: How do you recreate this bug or crash?
        description: Give us a list of steps in order to recreate the bug or crash.
        placeholder: |
          1. Do ...
          2. Then ...
          3. Do this ..., ... and then ...
          4. Observe "the bug" or "the crash"
    validations:
        required: true

  - type: textarea
    id: crash-log
    attributes:
        label: Errors
        description: Open the Developer Console with Ctrl/Cmd + Shift + i. On the top right click "Default levels", uncheck everything but don't uncheck "Errors" and paste them between the "```".
        value: |
          ```
          Replace this text with your crash-log. Do not remove the backticks.
          ```
    validations:
        required: false

  - type: checkboxes
    id: agreement-check
    attributes:
        label: Request Agreement
        description: We only accept reports for bugs that happen on Discord Stable. Canary and PTB are development branches and may be unstable.
        options:
            - label: I am using Discord Stable or tried on Stable and this bug still happens
              required: true
            - label: I have read the requirements for opening an issue above
              required: true
