name: Merge Upstream
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: Vendicated/Vencord
          upstream-branch: main
          branch: main
          token: ${{ secrets.GH_TOKEN }}
