name: Merge Upstream
on:
  schedule:
    - cron: "0 */4 * * *"
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge upstream
        run: |
          git config --global user.name 'pupbrained'
          git config --global user.email 'mars@pupbrained.xyz'

          git pull --unshallow

          git remote add upstream https://github.com/Vendicated/Vencord.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
