name: Merge Upstream
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Upstream
        uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: Vendicated
          base: main
          head: main
