name: test
on:
    push:
    pull_request:
        branches:
            - main
            - dev
permissions:
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
            - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

            - name: Use Node.js 20
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint & Test if desktop version compiles
              run: pnpm test

            - name: Test if web version compiles
              run: pnpm buildWeb

            - name: Test if plugin structure is valid
              run: pnpm generatePluginJson
